### PR TITLE
golook: fix generating of enum type array

### LINKED ISSUE #364: SupportedFormats not implemented in GoLook
Having an issue with the GoLook SDK, getting this error when trying to get dependencies, it seems that these structs were never implemented.
```
# github.com/looker-open-source/sdk-codegen/go/sdk/v3
../../../../pkg/mod/github.com/looker-open-source/sdk-codegen/go@v0.0.0-20201015075209-99828c0c7de3/sdk/v3/models.go:1079:40: undefined: SupportedFormats
../../../../pkg/mod/github.com/looker-open-source/sdk-codegen/go@v0.0.0-20201015075209-99828c0c7de3/sdk/v3/models.go:1080:40: undefined: SupportedActionTypes
../../../../pkg/mod/github.com/looker-open-source/sdk-codegen/go@v0.0.0-20201015075209-99828c0c7de3/sdk/v3/models.go:1081:40: undefined: SupportedFormattings
../../../../pkg/mod/github.com/looker-open-source/sdk-codegen/go@v0.0.0-20201015075209-99828c0c7de3/sdk/v3/models.go:1082:40: undefined: SupportedVisualizationFormattings
../../../../pkg/mod/github.com/looker-open-source/sdk-codegen/go@v0.0.0-20201015075209-99828c0c7de3/sdk/v3/models.go:1083:40: undefined: SupportedDownloadSettings
../../../../pkg/mod/github.com/looker-open-source/sdk-codegen/go@v0.0.0-20201015075209-99828c0c7de3/sdk/v3/models.go:1468:31: undefined: UserAttributeFilterTypes
```

### PR DESCRIPTION
**Pull request by kppk**
This should fix generating of array of enum type.

fixes #364

### CODE REVIEW

**Review by joeldodge79 — APPROVED** [review]
LGTM, thx!

File: go/sdk/v4/models.go [hunk 1]
```diff
@@ -31,7 +31,7 @@ SOFTWARE.
 */
 
 
-// NOTE: Do not edit this file generated by Looker SDK Codegen for Looker 7.18 API v4
+// NOTE: Do not edit this file generated by Looker SDK Codegen for Looker  API v4
```
Comment (jkaster) [inline go/sdk/v4/models.go:34]: Do you know why you've lost Looker version information here?
